Repository PDP-10/its, pull requests merged in 2018-08, with the labels that each got.

#1123 Update the markdown files in doc.
  doc/DDT.md
  doc/EMACS.md
  doc/TECO.md
  doc/debugging.md
  doc/hello-midas.md
Labels: documentation

#1109 Tweak Makefile to allow overriding of shell commands
  Makefile
Labels: enhancement, host

#1072 Fix IOPUSH scribbling random memory location
  src/system/ts3tty.401
Labels: bug

#1136 :SEND help text
  doc/_info_/ddt.:send
  doc/_info_/ddt.doc
  doc/_info_/ddt.order
Labels: todo

#1145 Fix wrong URL for KA10 simulator.
  .gitmodules
Labels: bug, host

#1149 Silence the system job by patching ITS on boot
  build/basics.tcl
  build/build.tcl
  build/ka10/include.tcl
  build/ks10/include.tcl
Labels: build process

#1150 Parallel CircleCI build with all three emulators.
  .circleci/config.yml
Labels: build process

#1156 "AR" RUG for Logo 11/45
  Makefile
  build/misc.tcl
  doc/programs.md
  src/rug/ar.632
Labels: todo

#1171 Assemble Tech II for TV display.
  build/misc.tcl
  src/agb/c.dis
Labels: game, todo

#1181 Fix typo; it should be TS CLOGO.
  build/misc.tcl
Labels: bug, host

#627 TIME, DATE, DATSRV fixed when .RDATE returns -1
  src/sysen2/time.28
  src/sysen3/date.3
  src/sysnet/datsrv.4
Labels: bug, easy

#1183 Reassemble ITS howto
  README.md
  doc/NITS.md
Labels: documentation

#1189 Login messages
  src/sys/net.mail
  src/sys/system.mail
Labels: documentation, easy
