Repository PDP-10/its, pull requests merged in 2018-06, with the labels that each got.

#950 Fix a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation, host

#956 Use <kbd> to mark control keys in the examples.
  doc/printing.md
Labels: documentation

#957 Build hangs on FreeBSD
  build/build.tcl
Labels: bug, host

#975 Fix 11BOOT/IOELEV build breakage
  build/misc.tcl
Labels: bug, host

#979 LEMOTE MIPS : build.tcl change
  build/muddle.tcl
Labels: bug, host

#988 Add SENSOR's manual.
  doc/info/sensor.2
Labels: documentation

#987 Fix assorted typos and formatting variations in programs.md.
  doc/programs.md
Labels: documentation

#126 TYPESQ - print out a squeezed file
  build/misc.tcl
  doc/programs.md
Labels: todo

#640 Build times out waiting for string
  Makefile
  build/emacs.tcl
Labels: bug, host

#993 Resolves #724. Build MLMAC from source.
  build/lisp.tcl
Labels: todo

#392 IMLOAD/IMTRAN - load or translate Imlac programs
  build/misc.tcl
  doc/_info_/imload.recent
  doc/programs.md
  src/syseng/imload.80
Labels: dynamic modeling

#1017 PDP-10 maintenance
  Makefile
  bin/maint/part.a
  bin/maint/part.b
  bin/maint/part.c
  bin/maint/part.e
  bin/maint/part.f
  bin/maint/part.g
  bin/maint/part.i
  bin/maint/part.j
  bin/maint/part.k
  bin/maint/part.l
  bin/maint/part.m
  build/misc.tcl
  doc/programs.md
  src/sysen2/10run.11
Labels: pdp6, todo

#636 SCAN - TeX output to XGP scan file
  build/misc.tcl
  doc/programs.md
  src/sysen1/scan.561
Labels: todo

#1034 Update FAIL manual
  doc/sail/fail.manual
Labels: documentation
