Repository PDP-10/its, pull requests merged in 2018-04, with the labels that each got.

#780 Reconstruct source code for FACTOR.
  build/build.tcl
  doc/_info_/factor.order
  src/sysen3/factor.100
Labels: reconstructed

#803 Add some LIFE data files.
  src/rwg/life.demo
  src/rwg/life.saved
  src/rwg/life.stuff
Labels: todo

#698 KA ITS to use TM10B
  build/sims/boot2
  build/sims/config.202
  build/sims/run
Labels: enhancement, host

#494 LSRPRT - print user group information
  build/build.tcl
  doc/programs.md
  src/sysen1/lsrprt.49
Labels: todo
