Repository PDP-10/its, pull requests merged in 2018-07, with the labels that each got.

#1045 CHESS - Unknown chess program.
  Makefile
  build/misc.tcl
  doc/programs.md
  src/as/chess.144
Labels: dynamic modeling, game

#1046 COOKIE BEAR - prank
  Makefile
  build/misc.tcl
  doc/programs.md
  src/gls/check.51
  src/gls/check.foo
Labels: todo

#1030 SYSTEM GEN - low level DECtape formatting
  build/misc.tcl
  doc/programs.md
  src/syseng/system.gen
Labels: pdp6

#1076 CCONS - CONS console, Datapoint emulator, and graphics display
  Makefile
  build/misc.tcl
  doc/programs.md
  src/lmcons/ccons.478
Labels: pdp11, todo

#1085 Disassemble FP11 floating point instructions in 11SIM.
  src/syseng/11sim.427
Labels: enhancement

#1087 Add FP11 instruction typein to 11SIM debugger.
  src/syseng/11sim.427
Labels: enhancement, pdp11

#1115 Fix typo in complr^K invocation when building ITSTER.
  build/lisp.tcl
Labels: bug, host
