Repository PDP-10/its, pull requests merged in 2018-03, with the labels that each got.

#692 Bill Gosper's MLIFE.
  Makefile
  README.md
  build/build.tcl
  src/rwg/mlife.21
Labels: todo

#679 MIDAS and CHESS2 don't work standalone
  build/build.tcl
Labels: bug, host

#696 Write files in . to DSK0:
  build/build.tcl
  build/ka10/include.tcl
  build/ks10/include.tcl
Labels: enhancement, host

#697 Remove duplicate KA ITS config.
  build/sims/config.202
Labels: bug

#540 COMRED - Lisp library for TOPS-20 command line
  build/build.tcl
  src/libdoc/comred.1
Labels: enhancement

#699 Update bootstrap ITS.
  bin/ks10/_/its.rp06
Labels: bug

#403 ITS version number history
  doc/README.md
  doc/versions.md
Labels: documentation, host

#619 PEEK uptime overflow
  src/sysen2/peek.630
Labels: bug

#705 Resolves #704. Renames SYS; PURQIO 1 to SYS; PURQIO 2154
  build/build.tcl
Labels: bug

#723 Add to contribution guidelines.
  CONTRIBUTING.md
Labels: enhancement, host

#760 Move build procedure and program list to separate files.
  README.md
  doc/build.md
  doc/programs.md
Labels: documentation, host

#761 Build with GitLab CI.
  .gitlab-ci.yml
  README.md
  build/dependencies.sh
Labels: enhancement, host

#759 Add Scheme interpreter to README.
  doc/programs.md
Labels: documentation, host

#765 Fix typo in emulator interrupt key.
  doc/DUMP-itstar.md
Labels: bug, documentation

#767 Update contribution guidelines.
  CONTRIBUTING.md
Labels: documentation, host

#474 SRDATE - set file reference date
  build/build.tcl
  doc/programs.md
  src/sysen3/srdate.13
Labels: todo

#463 CHAOSNET ARPA/NCP/TCP - Chaosnet to Arpanet/Internet gateway
  build/build.tcl
  doc/programs.md
  src/sysnet/arpa.66
Labels: todo

#773 Init and update submodule contents if they are empty.
  .gitlab-ci.yml
  Makefile
Labels: enhancement, host
