Repository PDP-10/its, pull requests merged in 2018-10, with the labels that each got.

#1274 Fixed typo in limerick
  src/eak/lims.7
Labels: bug

#1279 Fix wrong filename for timesharing NSALV.
  build/misc.tcl
Labels: bug

#1290 Fix link to TECO.
  build/emacs.tcl
Labels: bug, host

#1070 Add $. and $^N to exec DDT
  build/ka10/include.tcl
  build/misc.tcl
  doc/debugging.md
  src/system/ddt.69
Labels: enhancement

#1214 ULISP - Lisp in Lisp, for teaching
  Makefile
  build/lisp.tcl
  build/misc.tcl
  doc/programs.md
  src/teach/ulisp.459
Labels: todo

#942 VT07 - GT40 Datapoint terminal emulator
  Makefile
  bin/gt40/vt07.bin29
  doc/programs.md
Labels: pdp11, source missing

#1296 Fix GTLOAD to allow lower case input.
  src/syseng/gtload.14
Labels: bug

#1305 Update location of TCTYP; no link.
  build/basics.tcl
Labels: bug, host

#1273 Document PDSET command C
  doc/sysdoc/pdset.info
  src/sysen1/pdset.115
Labels: documentation, easy

#1198 METERD and SMETER
  build/misc.tcl
Labels: easy, todo

#1317 Added inquir; inqexm and inqrep. Created links for ts inqchk and ts inqpat
  build/lisp.tcl
  src/inquir/inqexm.101
  src/inquir/inqrep.32
Labels: todo

#510 ECHO - Chaosnet ECHO server
  build/misc.tcl
  doc/programs.md
  src/sysnet/echo.5
Labels: easy, todo

#1301 Add Chaosnet hosts to table
  build/h3text.2014
Labels: enhancement

#513 MAILS - Chaosnet mail server
  build/misc.tcl
  doc/programs.md
  src/sysnet/mails.54
Labels: easy, todo

#1333 Fix LSPEED valret when DL10 or DTE20 TTY not found.
  src/syseng/lspeed.20
Labels: bug

#1341 Fix KS10 SIMH script for GT40.
  build/simh/gt40
  build/simh/start
Labels: bug, host

#1342 Fix link for UPTIME Chaosnet server.
  build/misc.tcl
Labels: bug, host

#1349 IBMASC - read 8-bit ASCII tape file.
  build/misc.tcl
  doc/programs.md
  src/sysen1/ibmasc.1
Labels: todo

#1347 TTYTST - echo characters exactly as typed.
  build/misc.tcl
  doc/programs.md
  src/sysen2/ttytst.3
Labels: todo

#1348 DOWNLD - print file in super-image mode to TTY.
  build/misc.tcl
  doc/programs.md
  src/sysen1/downld.33
Labels: todo

#1350 LOTCLN - LOGOUT TIMES cleanup program.
  build/misc.tcl
  doc/programs.md
  src/sysen1/lotcln.4
Labels: todo

#1353 Emacs Lore
  Makefile
  doc/eak/emacs.lore
Labels: documentation

#1352 OINIT - init program reporting last login, email.
  build/misc.tcl
  doc/programs.md
  src/sysen2/oinit.8
Labels: todo

#1373 Build script occasionally hangs due to DAYLIGHT SAVINGS
  build/build.tcl
Labels: bug, host
