Repository PDP-10/its, pull requests merged in 2019-01, with the labels that each got.

#1328 QSEND
  build/emacs.tcl
  src/ejs/qsend.149
Labels: todo

#1476 If TVFIX runs without a TV-11, exit gracefully.
  src/sysen2/stuff.93
Labels: bug

#1470 ARCDEV 69 doesn't work
  src/syseng/arcdev.70
Labels: bug

#1477 Rearrange SALV and NSALV binaries.
  build/ka10/include.tcl
  build/ks10/include.tcl
Labels: bug, host

#702 Enable PD clock
  build/sims/config.202
  build/sims/run
Labels: todo

#1482 Make NAMDRG more graceful about missing TV-11
  src/sysen2/namdrg.149
Labels: bug

#1489 Fix TELNET to interoperate with buggy servers.
  src/sysnet/telnet.753
Labels: enhancement

#1121 Update DDT to use TV meta bucky bit
  src/sysen1/ddt.1547
Labels: enhancement, knight tv

#1427 Use H3MAKE
  Makefile
  bin/sysbin/hosts3.2013
  build/basics.tcl
Labels: host, question

#1517 Updated NSMDAT procedure in SYSNET; NETRTS > to fix hang during SMTP delivery
  src/sysnet/netrts.356
Labels: bug

#1501 Name Dragon pictures.
  src/channa/nampic.10
  src/channa/nampic.11
  src/channa/nampic.12
  src/channa/nampic.3
  src/channa/nampic.4
  src/channa/nampic.5
  src/channa/nampic.6
  src/channa/nampic.7
  src/channa/nampic.8
  src/channa/nampic.9
  src/channa/nampic.bag
  src/channa/nampic.down
  src/channa/nampic.dragon
  src/channa/nampic.fence
  src/channa/nampic.foo!
  src/channa/nampic.mitsel
  src/channa/nampic.peanut
  src/channa/nampic.ship
  src/channa/nampic.ship2
  src/channa/nampic.snupy!
  src/channa/nampic.snupy?
  src/channa/nampic.turtle
  src/channa/nampic.unicrn
  src/channa/nampic.world
  src/channa/nampic.wumpus
Labels: knight tv, todo

#509 BABEL - Chaosnet BABEL server
  Makefile
  build/misc.tcl
  doc/programs.md
  src/dcp2/babel.2
Labels: easy, todo
