Repository PDP-10/its, pull requests merged in 2019-02, with the labels that each got.

#1527 MINI36 - mini Chaosnet file server (36-bit).
  build/misc.tcl
  doc/programs.md
  src/kshack/mini36.2
Labels: todo

#512 HOSTAB - Chaosnet host table
  build/misc.tcl
  doc/programs.md
  src/eak/chahtb.22
Labels: todo

#1528 LISP11 - PDP-11 Lisp
  build/misc.tcl
  doc/programs.md
  src/rms/lisp11.265
Labels: pdp11, todo

#1532 Link from TS BOOT11 to 11STNK.
  build/misc.tcl
Labels: todo

#1543 TITLER - display text on color scope.
  Makefile
  build/misc.tcl
  doc/programs.md
  src/mb/titler.3
Labels: color display, todo

#935 PORNISM
  build/misc.tcl
  doc/programs.md
  src/rwg/pornis.24
Labels: pdp6, todo, type 340

#1537 A guide / short intro for ITS Logo versions #1496
  README.md
  doc/logo.md
Labels: documentation

#1547 Add check in build script when making a new directory.
  build/basics.tcl
  build/build.tcl
  build/lisp.tcl
  build/macsyma.tcl
  build/mark.tcl
  build/misc.tcl
  build/muddle.tcl
Labels: bug, host
