Repository PDP-10/its, pull requests merged in 2019-05, with the labels that each got.

#1597 Add some old .INFO. files.
  doc/_info_/?.info
  doc/_info_/^ddt.histry
  doc/_info_/its.info
Labels: documentation

#1602 Y2K fix for DECUUO's TIME emulation.
  src/decsys/decuuo.313
Labels: bug

#1601 Dover poem
  doc/humor/dover.poem
Labels: documentation, printing, todo

#1571 TORTIS
  Makefile
  build/misc.tcl
  doc/programs.md
  src/radia/tortis.31
Labels: logo, todo

#1612 Work around a Mac OS X/BSD bug requiring expect to send two \0 characters in a row.
  build/misc.tcl
Labels: bug, host
