Repository PDP-10/its, pull requests merged in 2019-06, with the labels that each got.

#1615 Minor changes in doc/logo.md
  doc/logo.md
Labels: documentation, logo

#1617 TST342 - display all Type 342 characters.
  Makefile
  build/misc.tcl
  doc/programs.md
  src/maint/tst342.108
Labels: type 340

#1619 Port TENTH to KA10 and PDP-6.
  src/aap/tenth.4
Labels: enhancement, pdp6

#1629 Damaged file
  Makefile
  bin/ks10/sys/ts.ksfedr
  bin/minsys/sys/atsign.ddt
  bin/minsys/sys/atsign.device
  bin/minsys/sys/atsign.hactrn
  bin/minsys/sys/msgs.times
  bin/minsys/sys/ts.ddt
  bin/minsys/sys/ts.lock
  bin/minsys/sys/ts.midas
  bin/minsys/sys/ts.pdset
Labels: bug

#909 FAILSA - Failsafe reader
  build/misc.tcl
  doc/programs.md
  src/moon/failsa.9
Labels: todo

#829 EMACS CHART bug
  src/_teco_/teco.1213
Labels: bug

#1008 .MLLIT bug?
  doc/info/midas.26
Labels: bug, documentation
