Repository PDP-10/its, pull requests merged in 2020-08, with the labels that each got.

#695 CUBE
  Makefile
  build/lisp.tcl
  doc/_info_/cube.info
  doc/bsg/cube.info
  doc/bsg/cube.templt
  src/bsg/cdriv.53
  src/bsg/cinput.16
  src/bsg/csolve.8
  src/bsg/csolve.dcls
  src/bsg/cube.8
  src/bsg/cube.dcls
  src/bsg/cubpkg.31
  src/bsg/cubrdf.4
  src/bsg/cutils.5
  src/bsg/cxfrm.7
  src/bsg/oonl.3
  src/bsg/qcolor.73
  src/bsg/qqc.54
Labels: game, todo

#903 BANNER
  build/misc.tcl
  doc/_info_/banner.info
  doc/programs.md
  src/sysen2/banner.92
Labels: dynamic modeling, printing, todo

#1926 Shorten tvbrot's iter loop
  src/lars/tvbrot.209
Labels: enhancement, knight tv

#1929 @ MARK
  bin/ka10/_/@.mark
  build/misc.tcl
  src/syseng/mark.1
Labels: reconstructed, source missing

#1930 MACDMP - standalone tool for loading/dumping DECtape files.
  build/misc.tcl
  doc/programs.md
  src/syseng/macdmp.6u32
  src/syseng/macdmp.moby1
Labels: pdp6, type 340

#1933 Move Zork to LCF;
  Makefile
  src/lcf/act1.254
  src/lcf/act2.92
  src/lcf/act3.199
  src/lcf/act4.231
  src/lcf/b.176
  src/lcf/build.cmd
  src/lcf/defs.171
  src/lcf/disp1.2
  src/lcf/dung.355
  src/lcf/impl.123
  src/lcf/makstr.44
  src/lcf/melee.137
  src/lcf/parser.130
  src/lcf/points.txt
  src/lcf/ppaper.txt
  src/lcf/prim.9
  src/lcf/rooms.394
  src/lcf/sr.54
  src/lcf/syntax.7
  src/lcf/tape.999
  src/lcf/tell.152
  src/lcf/typhak.16
  src/lcf/util.16
Labels: game, muddle

#1936 Remove MIDAS; MIDAS MACRO
  doc/midas/midas.macro
Labels: documentation

#1937 Add INFO; MIDAS ARCHIV
  doc/info/midas.archiv
Labels: documentation

#1925 Optionally hide Zork source code
  src/lcf/hide.zork
Labels: build process, dynamic modeling
