Repository PDP-10/its, pull requests merged in 2020-01, with the labels that each got.

#1795 Missing ';' to comment out mode-line.
  src/teach/errhel.38
Labels: bug

#1581 Minskytron
  build/misc.tcl
  doc/programs.md
  src/lars/minsky.tron
Labels: type 340

#1804 Readme updates.
  README.md
Labels: documentation, host

#1727 Make 340 display optional
  build/pdp10-ka/start
Labels: documentation, host, type 340

#1809 Fix TVFIX TOP LEVEL INTERRUPT
  src/sysen2/stuff.94
Labels: bug
